version: "3.7"

volumes:
  percona-data:

services:
#  api:
#    build:
#      dockerfile: api/Dockerfile
#    ports:
#      - 3000:3000

  adminer:
    image: adminer:5.3.0
    ports:
      - 8085:8080

  db:
    image: mysql:8.0
    environment:
      TZ: "Europe/Prague"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:   myappdb      # optional
      MYSQL_USER:       appuser
      MYSQL_PASSWORD:   supersecret
    volumes:
      - percona-data:/var/lib/mysql
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
