on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/client.yml'
  pull_request:
    paths:
      - 'client/**'
      - '.github/workflows/client.yml'

jobs:
  client-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install
      - run: pnpm build
